apiVersion: v2
name: zerotier
description: Helm chart for deploying a Zerotier member with optional secrets
type: application
version: 0.1.1
appVersion: "1.14.2"
kubeVersion: ">=1.24.0-0"
icon: https://www.zerotier.com/static/images/zt-icon.png
home: https://www.zerotier.com/
keywords:
  - zerotier
  - networking
  - vpn
sources:
  - https://github.com/zerotier/ZeroTierOne
maintainers:
  - name: Vitali Khlebko
    email: vitali.khlebko@vetal.ca

