apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zerotier.secretName" . }}
  labels:
    {{- include "zerotier.labels" . | nindent 4 }}
type: Opaque
data:
  devicemap: {{ printf "%s=%s" .Values.network.id .Values.network.interface | b64enc | quote }}
  identity.public: {{ .Values.identity.public | b64enc | quote }}
  identity.secret: {{ .Values.identity.private | b64enc | quote }}

