replicaCount: 1

image:
  repository: zerotier/zerotier
  tag: "1.14.2"
  pullPolicy: IfNotPresent

network:
  id: "<zerotier-net-id>"
  interface: "zt0"

deployment:
  nameOverride: ""
  fullnameOverride: ""
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  terminationGracePeriodSeconds: 30

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

containerSecurityContext:
  privileged: true
  allowPrivilegeEscalation: true
  readOnlyRootFilesystem: false
  runAsNonRoot: false

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

serviceAccount:
  create: false
  name: ""

secret:
  create: true
  nameOverride: ""
  data:
    identity.public: "<public-key>"
    identity.secret: "<private-key>"

initContainer:
  image: busybox
  tag: "1.35"
  command:
    - sh
    - -c
    - cp -v /data/* /var/lib/zerotier-one && chown -R 999:999 /var/lib/zerotier-one

volume:
  medium: ""

