apiVersion: v2
name: cert-manager
description: Cert-Manager chart for managing issuers and certificates
type: application
version: 0.2.0
appVersion: "1.0.0"
keywords:
  - cert-manager
  - letsencrypt
  - tls
  - certificate
maintainers:
  - name: Vitali Khlebko
    email: vitali.khlebko@vetal.ca

