apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openconnect.secretName" . }}
  labels:
    {{- include "openconnect.labels" . | nindent 4 }}
type: Opaque
data:
  ocpasswd: {{ default "" .Values.auth.users | b64enc | quote }}

